spring.application.name: api-gateway
server.port: 8084

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging.level:
  root: INFO
  org.springframework.cloud:
    gateway: TRACE
    gateway.route.RouteDefinition: INFO

## API Gateway routes configuration
spring.cloud.gateway.server.webflux:
  # product service route
  routes[0]:
    id: product-service
    uri: lb://product-service
    predicates[0]: Path=/api/products/**
  # order service route
  routes[1]:
      id: order-service
      uri: lb://order-service
      predicates[0]: Path=/api/orders/**
  # discovery server
  routes[2]:
    id: discovery-server
    uri: http://localhost:8761
    predicates[0]: Path=/eureka/web/
    filters[0]: SetPath=/
  # discovery server
  routes[3]:
    id: discovery-server-static
    uri: http://localhost:8761
    predicates[0]: Path=/eureka/**
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservice-realm

