spring.application.name: discovery-server
server.port: 8761
eureka:
  instance.hostname: localhost
  client.register-with-eureka: false # Disable self-registration as a service
  client.fetch-registry: false # Disable fetching registry ( since this is the server)
  server.enable-self-preservation: false # Disable self-preservation mode for development purposes
