spring.application.name: product-service
spring.data.mongodb.uri: mongodb://localhost:27017/product-service
server.port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/ # Eureka server URL with credentials (username-> eureka, password->  password)

# zipkin configuration for distributed tracing
spring:
  zipkin:
    base-url: http://localhost:9411/