spring.application.name: inventory-service
server.port: 8083

spring.datasource:
  url: jdbc:mysql://localhost:3306/inventory_service
  username: root
  password: root
spring.jpa.hibernate.ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
