spring.application.name: inventory-service
server.port: 8083

spring.datasource:
  url: jdbc:mysql://localhost:3306/inventory_service
  username: root
  password: root
spring.jpa.hibernate.ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/ # Eureka server URL with credentials (username-> eureka, password->  password)

# zipkin configuration for distributed tracing
management:
  tracing:
    sampling:
      probability: 1.0   # Capture 100% of traces (for testing)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans